### ISSUE TITLE
Sometimes starts more threads than it should?

### ISSUE THREAD

**Issue by famod** [mvndaemon/mvnd#362]
This might just be a display glitch, but sometimes when building Quarkus I can see something like: `threads used/hidden/max: 8/0/7`
This is on WSL2/Ubuntu 20.04.

In WSL1/Ubuntu 20.04 on my rather dated work laptop it even reaches `threads used/hidden/max: 12/0/7`.
When this happens the list of modules being built is actually that long (longer than it should be).

**Comment by gnodet** [comment]
I think logging statements may still be associated with a given project after it has been finished.  The client should disassociate those if they are sent after the project's build is finished.

**Comment by ppalaga** [comment]
What do you mean with "disassociate"? - not show them at all in the threaded view?

**Comment by gnodet** [comment]
> What do you mean with "disassociate"? - not show them at all in the threaded view?

Yes, they would be associated to the _main_ log instead of the _per project_ log.
The way the log are associated to projects is not 100% perfect, because of the lacking infrastructure in maven, so `mvnd` does its best.  Also ordering of the messages may be wrong : if the project's finish message arrives before one of the log, the client will recreate the project and it will kept in the display forever.

**Comment by gnodet** [comment]
Fixed by https://github.com/mvndaemon/mvnd/pull/367
