### ISSUE TITLE
Client hangs forever if the daemon crashes

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#47]
The daemon may crash for whatever reason, even without calling shutdown hooks. There should be a way for the client to find out that the daemon is down (so that client itself can exit).

**Comment by famod** [comment]
Just a quick thought: The daemon could touch a file periodically and the client could check if the file was touched recently. If not the daemon most likely crashed.

**Comment by gnodet** [comment]
Given we have a socket connection, we could simply send a simple keep-alive message from the daemon to the client every second (if nothing has been sent).  On the client side, if we haven't received anything since 3 seconds, we consider the daemon crashed.
That's really the same, but it reuses the current socket channel which is already opened.

**Comment by ppalaga** [comment]
> we could simply send a simple keep-alive message

Yeah, I also thought of that
