### ISSUE TITLE
Daemon forgets about maven settings on reuse

### ISSUE THREAD

**Issue by Postremus** [mvndaemon/mvnd#490]
I have a custom settings.xml which points to our company nexus.
On first start of the daemon, the settings get applied. Dependencies are downloaded from nexus.

On subsequent uses of the daemon however, the mirrors setting is not getting used. The daemon tries to download from maven central.
I now have to `mvnd --stop`, and then run the build again.

Log from subsequent runs:
```
[ERROR] project-web:1.0.0-SNAPSHOT: Unexpected message type 24: ExecutionFailure{projectId='project-web', halted=true, exception='org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project project-web: Could not resolve
 dependencies for project com.company:project-web-1.0.0-SNAPSHOT: com.company:commons:jar:1.1.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced'}
```

Settings.xml:
```
<mirrors>
		<mirror>
			<id>nexus_internal</id>
			<mirrorOf>internal</mirrorOf>
			<url>https://nexus03.company.com/repository/internal</url>
		</mirror>
		<mirror>
			<id>nexus_public</id>
			<mirrorOf>*</mirrorOf>
			<url>https://nexus03.company.com/repository/public</url>
		</mirror>
	</mirrors>
```

My mvnd.properties:
```
maven.settings=/Users/mnp/.m2/mvnd.properties
```

**Comment by rkraneis** [comment]
Same issue here; we apply such settings with an `activeByDefault` profile, which isn't activated ...

**Comment by rkraneis** [comment]
Unfortunately still happening with
> mvnd native client 0.7.0-linux-amd64 (0ebc71628ceb3bc37dc1d595fc02daa3e58c820f)

(But I guess that was to be expected, given the :+1:  :trollface:)

**Comment by gnodet** [comment]
The  👍 was mainly about the analysis : the fact that an `activeByDefault` profile isn't activated.
I'll try to replicate the problem in the coming days, but if you have some spare cycles, an integration test would be awesome !

**Comment by Postremus** [comment]
Can confirm, we also use `activeByDefault` to activate these settings / add more repositories.

**Comment by gnodet** [comment]
@rkraneis @Postremus I can't reproduce the problem with `activeByDefault` profiles.  Can you guys set up a reproducer project, maybe using a docker image using `xetusoss/archiva` or something similar to set up a mirror ? I've tried doing so, but the settings seem to be processed correctly.

**Comment by mschorsch** [comment]
Same issue (mvnd 0.7.1; Linux)

**Comment by mschorsch** [comment]
The issue seems to happen only in multi module projects.

**Comment by cheeghi** [comment]
I get the same problem using `mvnd 0.7.1-windows-amd64` (on OpenJDK 11) with the Quarkus quickstart project (that produced with the [quarkus create](https://quarkus.io/get-started/) command).
The project is not multi-module and it doesn't have `activeByDefault` profiles.
I tried `mvnd` on another maven project and it works fine, so it's something project-related.
I tried to reproduce it on Docker (using the `openjdk:11` image) without success, but I believe it's always reproducible by bootstrapping the Quarkus quickstart project on a Windows machine.

Anyways, I cloned the project and did some debugging (on the 0.7.1 release commit using the GraalVM 11 jdk), here what I found out:

On the first request (I executed a  `mvnd clean compile`) processed by the daemon the [DaemonMavenCli](https://github.com/apache/maven-mvnd/blob/97c587c11383a67b5bd0ff8388bd94c694b91c1e/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L238) has one `ConfigurationProcessor`:

![image](https://user-images.githubusercontent.com/18173454/147367571-91770a06-ccda-4802-85b8-67b9fcbe1095.png)

While on the second request (another `mvnd clean compile`), it has two (of the same type actually):

![image](https://user-images.githubusercontent.com/18173454/147367654-269ff915-fe00-4787-a484-accdd3e09f67.png)

This means that once it enters the [configure](https://github.com/apache/maven-mvnd/blob/97c587c11383a67b5bd0ff8388bd94c694b91c1e/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L1039) method (on the second request) it thinks that the user has provided a custom processor and it looks for a processor which isn't a *SettingsXmlConfigurationProcessor*, but since both of them are, none of the processors get executed:

![image](https://user-images.githubusercontent.com/18173454/147368166-03a25f6c-b025-4fef-a203-ffc28a5e8a88.png)

So, I was wondering why on the second round a new settings processor shows up. I saw that the [configurationProcessors](https://github.com/apache/maven-mvnd/blob/97c587c11383a67b5bd0ff8388bd94c694b91c1e/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L183) map is a `EntryMapAdapter` returned by the Plexus container and it doesn't allow *put* operations, so no one in the meantime could have added a new processor in the Map. So I looked into the map's entrySet and I found that in the end the processors are being saved into a `BeanCache` field within the `LocatedBeans` Plexus class. So I think that, at some point, something is updating this cache. It might be something classloader-related, since the two beans seem to come from two different **ClassRealms**:

![image](https://user-images.githubusercontent.com/18173454/147369306-2d47032e-1dcb-4ec5-a7a8-5324898040ee.png)

Now, I don't have much overview on the project and on Plexus/Sisu, so I don't know if simply removing duplicate processors from the Map could be the right solution, or if this is a sign of a "broader" problem (maybe of how classes are being loaded).

I hope this gives some more info on the problem.

**Comment by pptom** [comment]
I get the same problem using  `mvnd-0.7.1-linux-amd64`

**Comment by Min-200** [comment]
Has this problem been solved? I am 0.9.0 and still have qualified extra puzzles

**Comment by gnodet** [comment]
A PR with an integration test would be really nice to diagnose / debug this issue...

**Comment by Min-200** [comment]
I am a multi-module project, the same code, in the same daemon process, first compiled the first time can work, the second compilation error, error content for the submodule can not find the version number in the parent pom
<img width="556" alt="企业微信截图_16842282717058" src="https://github.com/apache/maven-mvnd/assets/24370420/d2503172-fc9c-47bd-ac36-79a384797630">

**Comment by gnodet** [comment]
@Min-200 Can you provide a simple reproducer project with basic instructions ?

**Comment by Min-200** [comment]
Is there a parameter that will allow me to stop the daemon if the mvnd build fails

**Comment by ppalaga** [comment]
> Is there a parameter that will allow me to stop the daemon if the mvnd build fails
no
