### ISSUE TITLE
An uncertain conflict on folder creation

### ISSUE THREAD

**Issue by wu-sheng** [mvndaemon/mvnd#525]
Hi, first of all, thank you for building this cool tool.
I am from Apache SkyWalking(https://github.com/apache/skywalking), which includes many maven modules, and we suffered slow building experience for a long time.

I tried this with `mvnd package`, it works super good. The build time is down to `1:18 min` from `nearly 5 mins`. 

But I am surprised when I run `mvnd clean package`, an error shows up.
![image](https://user-images.githubusercontent.com/5441976/145173660-e53cf27f-4653-4953-9236-94f6d24b03a6.png)

This folder should exist, but `clean` causes re-creation, which ends in error.

To reproduce this, you could run
```shell
> git clone https://github.com/apache/skywalking.git
> git submodule init
> git submodule update
> mvnd clean package
``` 

`./mvnw clean package` would be able to pass and `mvnd package` too.

**Comment by gnodet** [comment]
The `apache-skywalking-apm` runs the assembly goal and refers to files that are built by other modules.  Given `mvnd` uses a concurrent built, you need to ensure the `apache-skywalking-apm` has dependencies on those modules, else you'll hit this error, which is caused by the assembly mojo being run before or at the same time than the required modules.
Reopen if adding the required dependencies does not work.
