### ISSUE TITLE
Keep a changelog file

### ISSUE THREAD

**Issue by galegofer** [mvndaemon/mvnd#64]
It would be very cool if you can keep a Changelog file to keep track of all the changes that are done through the different releases.

**Comment by ppalaga** [comment]
If anybody would like to setup `charmixer/auto-changelog-action` or similar a PR is welcome.

**Comment by helpermethod** [comment]
Hi @ppalaga,

I may have some time tomorrow morning an would like to tackle this.

**Comment by oscerd** [comment]
I'll wait a bit for @helpermethod, otherwise I can jump in :-)

**Comment by helpermethod** [comment]
Hi @oscerd, feel free to chime in!

**Comment by ppalaga** [comment]
The job keeps failing due to `No common ancestor between 844f3ddd7f4278b2ba097d817def4c3b46d574e7 and 0.0.0` This has to do with the fact that we re-wrote the master to remove any EPL-licensed code. The `0.0.0` tag was made on the original master, so now after rewriting the master from the very beginning, `0.0.0` and the new master are fully disjoint. I'd solve that by removing the 0.0.0 tag - because it was a test release anyway, and it does no have much value. WDYT, @gnodet ?
