### ISSUE TITLE
Goals of mvnd

### ISSUE THREAD

**Issue by OPeyrusse** [mvndaemon/mvnd#71]
Do you have some goals in mind for `mvnd`? The introduction in the Readme states that this project borrows some techniques from Gradle and Takari.
Reading about the two projects, I see that Takari helps for parallel jobs, and Gradle has many features.

For example, do you plan to record the state of a maven project to automatically build changed modules?
Do you limit the scope to a daemon skipping the initialization of the VM and the parsing of the project?

**Comment by gnodet** [comment]
I don't think the scope is limited, but the goal is not to rewrite maven either.  My initial goal was to speed builds, so any improvement is welcomed.

Fwiw, I'm planning on experimenting the use of Test Impact Analysis for Apache Camel, so that's somewhat in line with the overal goal of {{mvnd}}.  Even if that's not something that can be brought inside {{mvnd}}, it's another technique that aims the same goal and that can be used in complement to {{mvnd}}.

Anyway, we welcome contributions if you're fancy helping !

**Comment by OPeyrusse** [comment]
So far, I only plan to be a mere user and welcome you for this project :smile: 
But I keep in mind your offer and I thank you for the answer.
